default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter pub get"
      sh "flutter build apk --release"

      firebase_app_distribution(
        app: "1:1021703418913:android:5707582d2ee10fe3069f60",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "mariioashraf1@gmail.com",
        release_notes: "First FastLane Firebase Distribution Stage Testing GitHub Actions"
      )
  end
end
